name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Echo CTF_FLAG
      run: echo ${{ secrets.CTF_FLAG }}
